// See https://aka.ms/new-console-template for more information
sbyte x = 100;
byte n1 = 126;
n1++;
int n2 = 1000;
int n3 = 2147483647;
long n4 = 2147483648L;
bool complete = false;
char gender = 'F';
char letter = '\u0041';//unicode
float n5 = 4.5f;
double n6 = 4.5;
string name = "Roshni Prasad";
object obj1 = "Mehwish Bhatti";
object obj2 = 4.5f;
int n7 = int.MinValue;
int n8 = int.MaxValue;
sbyte n9 = sbyte.MinValue;
decimal n10 = decimal.MaxValue;

Console.WriteLine(x);
Console.WriteLine(n1);
Console.WriteLine(n2);
Console.WriteLine(n3);
Console.WriteLine(n4);
Console.WriteLine(complete);
Console.WriteLine(gender);
Console.WriteLine(letter);
Console.WriteLine(n5);
Console.WriteLine(n6);
Console.WriteLine(name);
Console.WriteLine(obj1);
Console.WriteLine(obj2);
Console.WriteLine(n7);
Console.WriteLine(n8);
Console.WriteLine(n9);
Console.WriteLine(n10);
Console.WriteLine("Good Morning!");
Console.WriteLine("Good Afternoon!");
Console.Write("Good Morning!");
Console.Write("Good Afternoon!");
Console.WriteLine("Good Evening!");
Console.WriteLine("Good Night!");
